### PR TITLE
Update dependencies and Gridsome config

### PR DESCRIPTION
**Pull request by seangwright**
The current set of packages fails to install on Windows & OSX when using Node > 10.

Gridsome has also updated multiple versions since the code in this repo was committed.

While this repo works great for setting up a Stackbit demo, as soon as users want to edit code locally, the dev experience is likely going to be very poor.

I updated the packages so that this repo works on Node 12 and fixed all the uses of Gridsome APIs that have changed since the previously committed version.

### CODE REVIEW

**Comment by smnh** [comment]
@seangwright are these changes included in the original repo this repo was forked from? It is preferred to rebase this repo on top of the recent changes from the original repo, rather diverging the code of this repo from the original repo making it harder to bring updates. 

In other words. If I will update the code to match the code in https://github.com/gridsome/gridsome-starter-blog, will it have all the needed fixes?

**Comment by seangwright** [comment]
@smnh Not sure. That repo is still 12 months old and not using the latest version of the framework.

**Comment by smnh** [comment]
It seems that the latest commits in the upstream repository have similar changes to what is proposed in this PR, plus some additional changes:
https://github.com/gridsome/gridsome-starter-blog/compare/08c0057788a02d270d969002eeecb8dd9efb430b...761a1689b7aa500f51b540a645ad4ad1b9283442

The only differences are some minor versions in the package.json.

I suggest first [syncing this repo with the latest changes from the upstream repository](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork). Then, on top of these updates, we can add any additional changes if needed.

This is to prevent any future conflicts when updating this repo with the latest commits from the original repo.

**Comment by seangwright** [comment]
I created a new PR #2 which is a merge from the upstream master.

**Pull request closed without merging**
